input {
  file {
    path => "/usr/share/logstash/data/variant05_openstack_cloud.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    
    codec => multiline {
      pattern => "^%{TIMESTAMP_ISO8601}"
      negate => true
      what => "previous"
    }
  }
}

filter {
  # Дата PID Хост Компонент [Контекст] Сообщение
  grok {
    match => { 
      "message" => "%{TIMESTAMP_ISO8601:timestamp}%{SPACE}%{NUMBER:pid}%{SPACE}%{NOTSPACE:hostname}%{SPACE}%{NOTSPACE:component}%{SPACE}\[%{DATA:request_id}\]%{SPACE}(?<level_or_msg>.*)" 
    }
  }

  grok {
    match => { "level_or_msg" => "^%{LOGLEVEL:level}%{SPACE}%{GREEDYDATA:log_message}" }
    overwrite => [ "log_message" ]
  }
  
  if ![level] {
    mutate { add_field => { "level" => "INFO" } }
    mutate { rename => { "level_or_msg" => "log_message" } }
  }

  date {
    match => [ "timestamp", "yyyy-MM-dd HH:mm:ss.SSS" ]
    target => "@timestamp"
  }
}

output {
  opensearch {
    hosts => ["http://opensearch-node:9200"]
    index => "openstack-logs-main"
    ssl => false
    ssl_certificate_verification => false
  }
  opensearch {
    hosts => ["http://opensearch-node:9200"]
    index => "logs-zstd"
    ssl => false
    ssl_certificate_verification => false
  }
  opensearch {
    hosts => ["http://opensearch-node:9200"]
    index => "logs-zstd-no-dict"
    ssl => false
    ssl_certificate_verification => false
  }
    opensearch {
    hosts => ["http://opensearch-node:9200"]
    index => "logs-best-compression"
    ssl => false
    ssl_certificate_verification => false
  }
}